# Generated by Django 6.0.2 on 2026-02-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_address_order_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postal_code',
            new_name='pincode',
        ),
    ]
