# Generated by Django 6.0.2 on 2026-02-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_product_is_active_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(default='cod', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
